const C=window.AMSAC_CONFIG;let sb=null;
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const MENU=[["inicio","⌂","Início"],["plantel","👥","Plantel"],["competicoes","🏆","Competições"],["jogos","⚽","Jogos"],["presencas","✓","Presenças"],["pse","◉","PSE / Bem-estar"],["avaliacoes","★","Avaliações"],["medidas","⚖","Peso / IMC"],["convocatorias","☑","Convocatórias"],["estatisticas","▥","Estatísticas"],["relatorios","▤","Relatórios"],["multas","€","Multas"],["config","⚙","Configurações"]];
const DB={players:[],competitions:[],teams:[],games:[]};
let currentGame=null,timer=null,seconds=0;
function nav(active){let h=MENU.map(x=>`<button class="navBtn ${x[0]==active?"active":""}" onclick="showPage('${x[0]}')"><span class="navIcon">${x[1]}</span>${x[2]}</button>`).join("");$("#desktopNav").innerHTML=h;$("#mobilePanel").innerHTML=h}
function showPage(p){nav(p);$("#mobilePanel").classList.remove("show");({inicio,plantel,competicoes,jogos,presencas,pse,avaliacoes,medidas,convocatorias,estatisticas,relatorios,multas,config}[p]||inicio)()}
function head(a,b){$("#pageTitle").textContent=a;$("#pageSub").textContent=b}
function modal(h){$("#modalBody").innerHTML=h;$("#modal").classList.remove("hidden")}function closeModal(){$("#modal").classList.add("hidden")}
async function get(t,order=""){let q=sb.from(t).select("*");if(order)q=q.order(order);let r=await q;if(r.error){console.error(r.error);return[]}return r.data||[]}
async function load(){[DB.players,DB.competitions,DB.teams,DB.games]=await Promise.all([get("players","name"),get("competitions","name"),get("teams","name"),get("games","game_date")])}
function inicio(){head("Início","Painel da equipa");$("#content").innerHTML=`<div class="cards"><div class="card yellowTop"><div class="label">Jogadores</div><div class="metric">${DB.players.length}</div></div><div class="card"><div class="label">Competições</div><div class="metric">${DB.competitions.length}</div></div><div class="card"><div class="label">Jogos</div><div class="metric">${DB.games.length}</div></div><div class="card"><div class="label">Golos</div><div class="metric">${DB.games.reduce((a,g)=>a+(g.home_score||0),0)}</div></div></div><div class="section card"><h3>AMSAC Futsal Manager</h3><p class="muted">Gestão completa da equipa, sessões e jogo.</p></div>`}
function plantel(){head("Plantel","Jogadores");$("#content").innerHTML=`<div class="sectionHeader"><h3>Plantel</h3><button class="btn primary" onclick="playerForm()">＋ Adicionar</button></div><div class="list">${DB.players.map(p=>`<div class="row"><div class="person"><div class="avatar">${p.photo_url?`<img src="${esc(p.photo_url)}">`:esc((p.name||"?")[0])}</div><div><b>${esc(p.name)}</b><div class="muted">#${p.number||"-"} · ${esc(p.position||"")}</div></div></div><button class="btn light" onclick="playerForm('${p.id}')">Editar</button></div>`).join("")||'<div class="card empty">Sem jogadores.</div>'}</div>`}
function playerForm(id){let p=DB.players.find(x=>x.id===id)||{};modal(`<h2>${id?"Editar":"Adicionar"} jogador</h2><form class=form id=f><div class=two><label>Nome<input name=name required value="${esc(p.name)}"></label><label>Número<input name=number type=number value="${p.number||""}"></label></div><label>Posição<select name=position>${["GR","Fixo","Ala","Pivot"].map(x=>`<option ${p.position==x?"selected":""}>${x}</option>`).join("")}</select></label><label>Foto<input name=photo_url value="${esc(p.photo_url)}"></label><button class="btn primary">Guardar</button></form>`);$("#f").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),d={name:f.get("name"),number:f.get("number")||null,position:f.get("position"),photo_url:f.get("photo_url")||null};let r=id?await sb.from("players").update(d).eq("id",id):await sb.from("players").insert(d);if(r.error)return alert(r.error.message);closeModal();await load();plantel()}}
function competicoes(){head("Competições","Competições e equipas");$("#content").innerHTML=`<div class=toolbar><button class="btn primary" onclick=compForm()>＋ Competição</button><button class="btn dark" onclick=teamForm()>＋ Equipa / símbolo</button></div><div class=list>${DB.competitions.map(c=>`<div class=row><div><b>${esc(c.name)}</b><div class=muted>${esc(c.type)}</div></div></div>`).join("")||'<div class="card empty">Sem competições.</div>'}</div>`}
function compForm(){modal(`<h2>Nova competição</h2><form class=form id=f><label>Nome<input name=name required></label><label>Tipo<select name=type>${["Campeonato","Taça","Torneio","Amigável","Outros"].map(x=>`<option>${x}</option>`).join("")}</select></label><button class="btn primary">Guardar</button></form>`);$("#f").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),r=await sb.from("competitions").insert({name:f.get("name"),type:f.get("type")});if(r.error)return alert(r.error.message);closeModal();await load();competicoes()}}
function teamForm(){modal(`<h2>Equipa / símbolo</h2><form class=form id=f><label>Nome<input name=name required></label><label>URL do símbolo<input name=logo_url></label><button class="btn primary">Guardar</button></form>`);$("#f").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),r=await sb.from("teams").insert({name:f.get("name"),logo_url:f.get("logo_url")||null});if(r.error)return alert(r.error.message);closeModal();await load();competicoes()}}
function jogos(){head("Jogos","Calendário e jogo ao vivo");$("#content").innerHTML=`<div class=sectionHeader><h3>Jogos</h3><button class="btn primary" onclick=gameForm()>＋ Novo jogo</button></div><div class=list>${DB.games.map(g=>{let t=DB.teams.find(x=>x.id==g.opponent_team_id);return `<div class=row><div><b>AMSAC ${g.home_score||0} — ${g.away_score||0} ${esc(t?.name||"")}</b><div class=muted>${g.game_date||""}</div></div><button class="btn dark" onclick="openGame('${g.id}')">Abrir jogo</button></div>`}).join("")||'<div class="card empty">Sem jogos.</div>'}</div>`}
function gameForm(){modal(`<h2>Novo jogo</h2><form class=form id=f><label>Data<input name=date type=date required></label><label>Competição<select name=competition>${DB.competitions.map(c=>`<option value=${c.id}>${esc(c.name)}</option>`).join("")}</select></label><label>Adversário<select name=opponent>${DB.teams.map(t=>`<option value=${t.id}>${esc(t.name)}</option>`).join("")}</select></label><div class=two><label>Minutos/parte<input name=minutes type=number value=20></label><label>Partes<input name=halves type=number value=2></label></div><button class="btn primary">Criar jogo</button></form>`);$("#f").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),r=await sb.from("games").insert({game_date:f.get("date"),competition_id:f.get("competition")||null,opponent_team_id:f.get("opponent")||null,minutes_per_half:+f.get("minutes"),halves:+f.get("halves")}).select().single();if(r.error)return alert(r.error.message);closeModal();await load();openGame(r.data.id)}}
async function squad(id){let r=await sb.from("game_squads").select("*").eq("game_id",id);return r.data||[]}
async function openGame(id){currentGame=DB.games.find(x=>x.id==id);let t=DB.teams.find(x=>x.id==currentGame.opponent_team_id),sq=await squad(id);let starters=sq.filter(x=>x.role=="starter").map(x=>x.player_id),subs=sq.filter(x=>x.role=="sub").map(x=>x.player_id);head("Jogo ao vivo","AMSAC · "+(t?.name||"Adversário"));$("#content").innerHTML=`<div class=gameHero><div class=team>AMSAC</div><div><div class=clock id=clock>00:00</div><div class=score>${currentGame.home_score||0} — ${currentGame.away_score||0}</div></div><div class=team>${esc(t?.name||"Adversário")}</div></div><div class=section><div class=quickGrid><button class=quickBtn onclick=startClock()>▶<br>Iniciar</button><button class=quickBtn onclick=stopClock()>⏸<br>Pausar</button><button class=quickBtn onclick=goalForm('${id}')>＋1 GOLO<br><small>marcador · assistência · zona</small></button><button class=quickBtn onclick=subForm('${id}')>↔<br>Substituição</button></div></div><div class="section card"><div class=sectionHeader><h3>5 inicial</h3><span class=tag>${starters.length}/5</span></div><div class=quickGrid>${DB.players.map(p=>`<button class="quickBtn ${starters.includes(p.id)?"primary":""}" onclick="toggleSquad('${id}','${p.id}','starter')">${esc(p.name)}</button>`).join("")}</div><div class=sectionHeader style="margin-top:15px"><h3>7 suplentes</h3><span class=tag>${subs.length}/7</span></div><div class=quickGrid>${DB.players.filter(p=>!starters.includes(p.id)).map(p=>`<button class="quickBtn ${subs.includes(p.id)?"primary":""}" onclick="toggleSquad('${id}','${p.id}','sub')">${esc(p.name)}</button>`).join("")}</div></div><div class="section card"><h3>Estatística rápida</h3><div class=quickGrid>${["REMATE 🥅","FORA","PERDA","RECUPERAÇÃO","FC","FS","CA 🟨","CV 🟥"].map(a=>`<button class=quickBtn onclick="eventForm('${id}','${a}')">${a}</button>`).join("")}</div></div>`}
async function toggleSquad(g,p,role){let existing=await sb.from("game_squads").select("*").eq("game_id",g).eq("player_id",p).maybeSingle();if(existing.data){if(existing.data.role==role){await sb.from("game_squads").delete().eq("id",existing.data.id)}else await sb.from("game_squads").update({role}).eq("id",existing.data.id)}else{let list=await squad(g);let n=list.filter(x=>x.role==role).length;if((role=="starter"&&n>=5)||(role=="sub"&&n>=7))return;await sb.from("game_squads").insert({game_id:g,player_id:p,role})}openGame(g)}
function eventForm(g,type){modal(`<h2>${type}</h2><div class=quickGrid>${DB.players.map(p=>`<button class=quickBtn onclick="saveEvent('${g}','${p.id}','${type}')">${esc(p.name)}</button>`).join("")}</div>`)}
async function saveEvent(g,p,type){let r=await sb.from("game_events").insert({game_id:g,player_id:p,event_type:type,minute:Math.round(seconds/60),value:{}});if(r.error)return alert(r.error.message);closeModal()}
function goalForm(g){modal(`<h2>＋1 Golo</h2><form class=form id=goal><label>Marcador<select name=player>${DB.players.map(p=>`<option value=${p.id}>${esc(p.name)}</option>`).join("")}</select></label><label>Assistência<select name=assist><option value="">Sem assistência</option>${DB.players.map(p=>`<option value=${p.id}>${esc(p.name)}</option>`).join("")}</select></label><label>Motivo<select name=reason>${["Organização ofensiva","Transição","5x4","Canto","Livre","Penálti","Outro"].map(x=>`<option>${x}</option>`).join("")}</select></label><b>Zona do remate</b><div class=quickGrid>${["Sup. esq.","Sup. centro","Sup. dir.","Centro esq.","Centro","Centro dir.","Inf. esq.","Inf. centro","Inf. dir."].map(x=>`<button type=button class=quickBtn onclick="this.parentElement.querySelectorAll('.primary').forEach(x=>x.classList.remove('primary'));this.classList.add('primary');this.dataset.zone='${x}'">${x}</button>`).join("")}</div><button type=button class="btn primary" onclick="saveGoal('${g}')">Confirmar golo</button></form>`)}
async function saveGoal(g){let f=new FormData($("#goal")),z=$("#goal [data-zone].primary");if(!z)return alert("Seleciona a zona da baliza.");let game=DB.games.find(x=>x.id==g);await sb.from("game_events").insert({game_id:g,player_id:f.get("player"),event_type:"GOLO",minute:Math.round(seconds/60),value:{assist:f.get("assist"),reason:f.get("reason"),zone:z.dataset.zone}});await sb.from("games").update({home_score:(game.home_score||0)+1}).eq("id",g);closeModal();await load();openGame(g)}
function subForm(g){modal(`<h2>Substituição</h2><div class=two><label>Sai<select id=out>${DB.players.map(p=>`<option value=${p.id}>${esc(p.name)}</option>`).join("")}</select></label><label>Entra<select id=in>${DB.players.map(p=>`<option value=${p.id}>${esc(p.name)}</option>`).join("")}</select></label></div><br><button class="btn primary" onclick="saveSub('${g}')">Confirmar</button>`)}
async function saveSub(g){await sb.from("game_events").insert({game_id:g,event_type:"SUBSTITUICAO",minute:Math.round(seconds/60),value:{out:$("#out").value,in:$("#in").value}});closeModal()}
function startClock(){if(timer)return;timer=setInterval(()=>{seconds++;$("#clock").textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`},1000)}
function stopClock(){clearInterval(timer);timer=null}
async function presencas(){head("Presenças","Sessões de treino");let d=new Date().toISOString().slice(0,10);$("#content").innerHTML=`<div class=sectionHeader><h3>Presenças · ${d}</h3><button class="btn primary" onclick=allPresent()>Todos presentes</button></div><div class=list>${DB.players.map(p=>`<div class=row><div class=person><div class=avatar>${esc(p.name[0])}</div><b>${esc(p.name)}</b></div><select onchange="setAttendance('${p.id}',this.value)">${["P","PA","L","D","FJ","FI","TS","JS","SEL","O"].map(x=>`<option>${x}</option>`).join("")}</select></div>`).join("")}</div><p class=muted>P Presente · PA Atraso · L Lesionado · D Doente · FJ Falta justificada · FI Falta injustificada · TS/JS/SEL/Outro</p>`}
async function setAttendance(p,s){let d=new Date().toISOString().slice(0,10);await sb.from("attendances").upsert({player_id:p,session_date:d,status:s},{onConflict:"player_id,session_date"})}
async function allPresent(){let d=new Date().toISOString().slice(0,10);for(let p of DB.players)await setAttendance(p.id,"P");presencas()}
async function pse(){head("PSE / Bem-estar","Recolha pós sessão");let d=new Date().toISOString().slice(0,10);$("#content").innerHTML=`<div class=card><div class=toolbar><input id=pseDate type=date value=${d}><select id=pseType><option>Treino</option><option>Jogo</option></select></div><h3>PSE · CR10</h3><div class=list>${DB.players.map(p=>`<div class=row><b>${esc(p.name)}</b><div class=toolbar>${[1,2,3,4,5,6,7,8,9,10].map(n=>`<button class=btn onclick="savePSE('${p.id}',${n})">${n}</button>`).join("")}</div></div>`).join("")}</div></div><div class=section card><h3>Bem-estar · 1 a 5</h3>${DB.players.map(p=>`<div class=row><b>${esc(p.name)}</b><div class=toolbar>${["sleep","fatigue","soreness","stress","mood"].map(k=>`<select onchange="saveWell('${p.id}','${k}',this.value)"><option value="">${k}</option>${[1,2,3,4,5].map(n=>`<option>${n}</option>`).join("")}</select>`).join("")}</div></div>`).join("")}</div>`}
async function savePSE(p,v){await sb.from("pse").upsert({player_id:p,session_date:$("#pseDate").value,session_type:$("#pseType").value,value:v},{onConflict:"player_id,session_date,session_type"})}
async function saveWell(p,k,v){if(!v)return;let d={player_id:p,session_date:new Date().toISOString().slice(0,10)};d[k]=+v;await sb.from("wellness").upsert(d,{onConflict:"player_id,session_date"})}
async function avaliacoes(){head("Avaliações","Psicológico · físico · tático · técnico");$("#content").innerHTML=`<div class=card><label>Jogador<select id=ap>${DB.players.map(p=>`<option value=${p.id}>${esc(p.name)}</option>`).join("")}</select></label><div class=quickGrid style="margin-top:15px">${["psychological","physical","tactical","technical"].map(k=>`<label>${k}<select id=${k}>${[1,2,3,4,5,6,7,8,9,10].map(n=>`<option>${n}</option>`).join("")}</select></label>`).join("")}</div><br><button class="btn primary" onclick=saveEval()>Guardar avaliação</button></div>`}
async function saveEval(){let d={player_id:$("#ap").value,evaluation_date:new Date().toISOString().slice(0,10),psychological:+$("#psychological").value,physical:+$("#physical").value,tactical:+$("#tactical").value,technical:+$("#technical").value};let r=await sb.from("evaluations").upsert(d,{onConflict:"player_id,evaluation_date"});if(r.error)alert(r.error.message)}
async function medidas(){head("Peso / IMC","Medições");$("#content").innerHTML=`<div class=list>${DB.players.map(p=>`<div class=row><b>${esc(p.name)}</b><div class=toolbar><input id=w_${p.id} placeholder="kg" type=number step=.1><input id=h_${p.id} placeholder="altura cm" type=number><button class=btn primary onclick="saveMeasure('${p.id}')">Guardar</button></div></div>`).join("")}</div>`}
async function saveMeasure(p){let w=+$("#w_"+p).value,h=+$("#h_"+p).value;if(!w||!h)return;let r=await sb.from("measurements").insert({player_id:p,measurement_date:new Date().toISOString().slice(0,10),weight:w,height:h,period:"Atual"});if(r.error)alert(r.error.message)}
function convocatorias(){head("Convocatórias","Preparação do jogo");$("#content").innerHTML=`<div class=card><h3>Selecionar jogo</h3><select id=cg>${DB.games.map(g=>`<option value=${g.id}>${g.game_date}</option>`).join("")}</select><h3>Jogadores</h3>${DB.players.map(p=>`<label style="display:block;margin:8px"><input type=checkbox value=${p.id}> ${esc(p.name)}</label>`).join("")}<button class="btn primary" onclick=saveCall()>Guardar convocatória</button></div>`}
function saveCall(){alert("Convocatória preparada. A gravação definitiva será ligada à tabela de convocatórias na próxima migração.")}
function estatisticas(){head("Estatísticas","Resumo");$("#content").innerHTML=`<div class=cards><div class=card><div class=label>Jogos</div><div class=metric>${DB.games.length}</div></div><div class=card><div class=label>Jogadores</div><div class=metric>${DB.players.length}</div></div><div class=card><div class=label>Golos</div><div class=metric>${DB.games.reduce((a,g)=>a+(g.home_score||0),0)}</div></div></div>`}
async function relatorios(){head("Relatórios","Análise");$("#content").innerHTML=`<div class=card><h3>Relatório</h3><p class=muted>Os dados de presenças, PSE, avaliações e jogos já estão estruturados para agregação.</p></div>`}
function multas(){head("Multas","Motivos e registos");$("#content").innerHTML=`<div class=card><h3>Motivos pré-definidos</h3><p class=muted>Falta injustificada · atraso · material · comportamento · outros</p></div>`}
function config(){head("Configurações","AMSAC Futsal Manager");$("#content").innerHTML=`<div class=card><h3>Ligação Supabase</h3><p class=muted>Base de dados ligada.</p></div>`}
async function init(){if(window.supabase)sb=window.supabase.createClient(C.supabaseUrl,C.supabaseKey);await load();showPage("inicio")}
init();